<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
	<!-- FIXES MSB3030: Prevents the SDK from trying to look for a non-existent obj\app.config file -->
	<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
	<!-- FIXED MSB3823 -->
	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <OutputType>Library</OutputType>
    <MyType>Windows</MyType>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<!-- Assembly Metadata -->
	<Title>Basic Tools</Title>
	<Description>Allows some basic WinForms controls and functions to support in building Mod Editors.</Description>
	<Company>Cetra Studios</Company>
	<Product>Basic Tools for Mod Editors</Product>
	<Copyright>©  2014 Cetra Studios</Copyright>

	<!-- Versioning -->
	<Version>0.8.0.0</Version>
	<AssemblyVersion>0.8.0.0</AssemblyVersion>
	<FileVersion>0.8.0.0</FileVersion>

	<!-- COM and Interop Settings -->
	<ComVisible>false</ComVisible>
	<Guid>9ffb9e7b-6b3b-4187-a9db-d095b5971b46</Guid>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\BasicTools.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\BasicTools.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>
  <PropertyGroup>
    <OptionCompare>Binary</OptionCompare>
  </PropertyGroup>
  <PropertyGroup>
    <OptionStrict>Off</OptionStrict>
  </PropertyGroup>
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Design" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.ComponentModel" />
    <Import Include="System.Data" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BasicControls.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="BasicBitFlag.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="BasicBitFlags.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="BasicColorSwatch.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="BasicExperimentalControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="obj\app.config" />
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="My Resources\arrow_pointer_down_16.png" />
    <Content Include="My Resources\arrow_pointer_up_16.png" />
    <Content Include="My Resources\arrow_sans_down_16.png" />
    <Content Include="My Resources\arrow_sans_down_16_with_seperator.png" />
    <Content Include="Resources\OrderedList.png" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{94E38DFF-614B-4CBD-B67C-F211BB35CE8B}" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AnyClone" Version="1.1.6" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="VisualBasic.PowerPacks.Vs" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
	  <!-- Explicitly forces the compiler to build the missing Trademark attribute -->
	  <AssemblyAttribute Include="System.Reflection.AssemblyTrademarkAttribute">
	    <_Parameter1>MakoInfused / Dino Suvalic</_Parameter1>
	  </AssemblyAttribute>
  </ItemGroup>
</Project>