<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <OutputType>Library</OutputType>
    <MyType>Windows</MyType>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<!-- Assembly Metadata -->
	<Title>Hex Tools</Title>
	<Description>Allows robust WinForms and WPF controls and functions to build Mod Editors by way of configuring: offsets, pointers, algorithms and visual components.</Description>
	<Company>Cetra Studios</Company>
	<Product>Hex Tools for Mod Editors</Product>
	<Copyright>©  2014 Cetra Studios</Copyright>

	<!-- Versioning -->
	<Version>0.8.0.0</Version>
	<AssemblyVersion>0.8.0.0</AssemblyVersion>
	<FileVersion>0.8.0.0</FileVersion>

	<!-- COM and Interop Settings -->
	<ComVisible>false</ComVisible>
	<Guid>1e2445fe-f424-45a9-b829-b51c5577ca3d</Guid>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\HexTools.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\HexTools.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>
  <PropertyGroup>
    <OptionCompare>Binary</OptionCompare>
  </PropertyGroup>
  <PropertyGroup>
    <OptionStrict>Off</OptionStrict>
  </PropertyGroup>
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="BasicTools">
      <HintPath>..\BasicTools\bin\Debug\BasicTools.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Design" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.ComponentModel" />
    <Import Include="System.Data" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="HexAddress.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HexAddressBox.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HexPalette.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HexByteViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HexDeveloper.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HexEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HexMessageBox.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="HexViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Sprite.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{94E38DFF-614B-4CBD-B67C-F211BB35CE8B}" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="VisualBasic.PowerPacks.Vs" Version="1.0.0" />
    <PackageReference Include="WPFHexaEditor" Version="2.1.7" />
  </ItemGroup>
  <ItemGroup>
	<!-- Explicitly forces the compiler to build the missing Trademark attribute -->
	<AssemblyAttribute Include="System.Reflection.AssemblyTrademarkAttribute">
	    <_Parameter1>MakoInfused / Dino Suvalic</_Parameter1>
	</AssemblyAttribute>
   </ItemGroup>
</Project>